import 'package:dartz/dartz.dart';
import '../../../../core/error/exceptions.dart';
import '../../../../core/error/failures.dart';
import '../../../../core/network/network_info.dart';
import '../../domain/entities/schedule_entity.dart';
import '../../domain/repositories/schedule_repository.dart';
import '../datasources/schedule_remote_datasource.dart';
import '../mappers/schedule_mapper.dart';
import '../models/schedule_model.dart';

/// Implementation of ScheduleRepository
class ScheduleRepositoryImpl implements ScheduleRepository {
  ScheduleRepositoryImpl({
    required this.remoteDataSource,
    required this.networkInfo,
  });
  final ScheduleRemoteDataSource remoteDataSource;
  final NetworkInfo networkInfo;

  @override
  Future<Either<Failure, List<ScheduleEntity>>> getSchedules({
    required String plotId,
    ScheduleType? filterType,
    int? limit,
  }) async {
    try {
      final isConnected = await networkInfo.isConnected;
      if (!isConnected) {
        return const Left(Failure.network(message: 'No internet connection'));
      }

      final scheduleModels = await remoteDataSource.getSchedules(
        plotId: plotId,
        type: filterType?.value,
        limit: limit,
      );

      final scheduleEntities =
          scheduleModels.map(ScheduleMapper.toEntity).toList();

      return Right(scheduleEntities);
    } on NetworkException catch (e) {
      return Left(Failure.network(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } on ServerException catch (e) {
      return Left(Failure.server(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } catch (e) {
      return Left(Failure.unknown(
        message: 'Failed to get schedules: ${e.toString()}',
        error: e,
      ));
    }
  }

  @override
  Future<Either<Failure, ScheduleEntity>> createSchedule({
    required String plotId,
    required ScheduleType type,
    required String title,
    required DateTime scheduledDate,
    String? description,
    List<String> activityIds = const [],
    bool isCompleted = false,
  }) async {
    try {
      final isConnected = await networkInfo.isConnected;
      if (!isConnected) {
        return const Left(Failure.network(message: 'No internet connection'));
      }

      final now = DateTime.now();
      final scheduleModel = await remoteDataSource.createSchedule(
        ScheduleModel(
          id: '', // Will be generated by backend
          plotId: plotId,
          type: type.value,
          title: title,
          description: description ?? '',
          scheduledDate: scheduledDate,
          activityIds: activityIds,
          isCompleted: isCompleted,
          createdAt: now,
          updatedAt: now,
        ),
      );

      final scheduleEntity = ScheduleMapper.toEntity(scheduleModel);
      return Right(scheduleEntity);
    } on NetworkException catch (e) {
      return Left(Failure.network(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } on ServerException catch (e) {
      return Left(Failure.server(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } catch (e) {
      return Left(Failure.unknown(
        message: 'Failed to create schedule: ${e.toString()}',
        error: e,
      ));
    }
  }

  @override
  Future<Either<Failure, ScheduleEntity>> updateSchedule(
      ScheduleEntity schedule) async {
    try {
      final isConnected = await networkInfo.isConnected;
      if (!isConnected) {
        return const Left(Failure.network(message: 'No internet connection'));
      }

      final scheduleModel = ScheduleMapper.toModel(schedule);
      final updatedModel = await remoteDataSource.updateSchedule(scheduleModel);
      final updatedEntity = ScheduleMapper.toEntity(updatedModel);

      return Right(updatedEntity);
    } on NetworkException catch (e) {
      return Left(Failure.network(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } catch (e) {
      return Left(Failure.unknown(
        message: 'Failed to update schedule: ${e.toString()}',
        error: e,
      ));
    }
  }

  @override
  Future<Either<Failure, void>> deleteSchedule(String scheduleId) async {
    try {
      final isConnected = await networkInfo.isConnected;
      if (!isConnected) {
        return const Left(Failure.network(message: 'No internet connection'));
      }

      await remoteDataSource.deleteSchedule(scheduleId);
      return const Right(null);
    } on NetworkException catch (e) {
      return Left(Failure.network(
        message: e.message,
        statusCode: e.statusCode,
      ));
    } catch (e) {
      return Left(Failure.unknown(
        message: 'Failed to delete schedule: ${e.toString()}',
        error: e,
      ));
    }
  }
}
